version: '3.9'

services:
  database:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_PASSWORD=password"
  app:
    build: .
    command: python main.py
    ports:
      - "80:80"
      - "433:433"
    depends_on:
      - database
    links:
      - "database"